os: osx
osx_image: xcoode9.2
language: ruby
rvm:
  - 2.0.0-p247
script:
  - brew list
  - echo $PATH
  - sudo rm -rf /usr/local/Homebrew
  - travis_wait 60 sudo rvm implode --force
  - openssl s_client -connect api.github.com:443
  - openssl version
  - ruby --version
  - ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
before_install:
  - rvm list rubies
  - sudo gem install bundler -v '~> 1.16'
